'
' TYPO3 PlantUML Stylesheet
' @see https://plantuml-documentation.readthedocs.io/en/latest/formatting/all-skin-params.html
'
skinparam ArrowColor #f49700
skinparam BackgroundColor #FFFFFF
skinparam DefaultFontColor #333333
skinparam Padding 8
skinparam ParticipantBackgroundColor #868e96
skinparam ParticipantBorderColor #f49700
skinparam ParticipantFontColor #FFFFFF
skinparam SequenceLifeLineBorderColor #f49700
skinparam Shadowing false
